### PR TITLE
New Cards

### PR DESCRIPTION
**Pull request by Mbrick2**
Should look nicer.
(I dont have a vercel account so I cant check the deployment)

### CODE REVIEW

**Comment by imdevarsh** [comment]
The text is white...
on a white background
image
By the way the Preview links are what you click. https://wininfo-git-fork-aipointdev-main-jaydendev.vercel.app/

**Comment by Mbrick2** [comment]
> The text is white... on a white background image By the way the Preview links are what you click. https://wininfo-git-fork-aipointdev-main-jaydendev.vercel.app/

Weird. It was red when I checked.

**Comment by imdevarsh** [comment]
You don't need to make a `cardtext` div - just use the `card` selector...

**Comment by Mbrick2** [comment]
> You don't need to make a `cardtext` div - just use the `card` selector...

I know. Im just superstitious when it comes to something that could mess code up

**Comment by jdev082** [comment]
btw red goes completely against the black and white color scheme of Windows 11 UX. I'd prefer stuff that was like Windows 11.
Windows 11 design with a crimson accent color is what im doing

**Comment by Mbrick2** [comment]
> Windows 11 design with a crimson accent color is what im doing

I used crimson

**Comment by jdev082** [comment]
Your PR is now not needed, as the switch to Tailwind has been completed.

**Pull request closed without merging**
