### PR TITLE
Optimisations

### LINKED ISSUE #15: Design Changes 19.2.2022
These are very necessary:

1. Make search bar consistent with the rest of the interface.
2. Make search bar take entire page width

### PR DESCRIPTION
**Pull request by imdevarsh**
- Adds const instead of let/var
- Remove google forms link
- Make search bar fill screen
- Structure warnings CSS
- Remove `console.log` which I left in #13 by accident
- Remove the body selector (doesn't do anything, in svelte it is scoped)
- Remove the `fakecommit` file (use `--allow-empty` instead)

Fixes #15 (but what does the first thing mean?)

### CODE REVIEW

**Comment by jdev082** [comment]
--allow-empty cannot be used when I make quick changes in GitHub itself and want to test the auto release thingy

**Comment by jdev082** [comment]
Also at one point, the card holding all the OS's took full screen width, are you using the latest source in your PR?

**Comment by jdev082** [comment]
This PR appears finished. Are you going to mark it ready?

**Comment by kccuber-scratch** [comment]
Why is everything so clumped together? It looks like it was made to be used on an iPad in vertical orientation.

**Comment by imdevarsh** [comment]
Oh right!! I know!


> Why is everything so clumped together? It looks like it was made to be used on an iPad in vertical orientation.

Removed some width thing while trying to make it responsive. Sorry

**Comment by imdevarsh** [comment]
> This PR appears finished. Are you going to mark it ready?

I'm still working on it.. I'm not a worker for you I am just a volunteer

**Comment by kccuber-scratch** [comment]
I think we should wait until #17 is merged before merging this as there's some conflicts (mainly the remove google form)

**Comment by imdevarsh** [comment]
OK that's fine!

**Comment by imdevarsh** [comment]
ready

**Pull request merged**
