### PR TITLE
Add Nicer cards

### PR DESCRIPTION
**Pull request by Mbrick2**
Sorry. Don't have time to do a full test

### CODE REVIEW

**Comment by jdev082** [comment]
Vercel tests it, and the build failed.

**Comment by jdev082** [comment]
you don't modify global.css, you modify themes.css and App.svelte

**Comment by jdev082** [comment]
Attempted to close a <div> that was not open...

**Review by imdevarsh — CHANGES_REQUESTED** [review]
Put it on https://github.com/JaydenDev/osinfo/pull/21/files#diff-d68daa8b73cec8e4419759802bbd91e9f87f8ee02f25cdb1d12582ef6de848dbR195

**Comment by Mbrick2** [comment]
Im redoing

**Pull request closed without merging**
