### PR TITLE
Add search

### PR DESCRIPTION
**Pull request by imdevarsh**

### CODE REVIEW

**Comment by jdev082** [comment]
the build failed...

**Comment by jdev082** [comment]
```
<html><body>
<!--StartFragment-->

[!] (plugin svelte) ParseError: </div> attempted to close an element that was not open
--


<span>ParseError: &lt;/div&gt; attempted to close an element that was not open</span><!--EndFragment-->
</body>
</html>
```

**Comment by jdev082** [comment]
also go ahead and add my latest commits to your PR to make it up to date.

**Comment by jdev082** [comment]
just merged and fixed the bug

**Comment by imdevarsh** [comment]
What

**Pull request merged**
